### ISSUE TITLE
Balance Sync

### ISSUE THREAD

**Issue by johncantrell97** [LN-Juggernaut/juggernaut-desktop#14]
Currently there's an issue where the (confirmed and unconfirmed) balance displayed in the main menu does not update after launching into a wallet.  You need to logout and log back in for it to update.  

We currently subscribe (via polling) getInfo grpc call that will return updated balance information every 5 seconds.  We should add a listener and handler for this event in walletSlice to update this value.  

Also remember to remove the listener in walletAPI (disconnectWallet).

To reproduce/test this issue you can:

1) launch into wallet
2) note your balance
3) open or close a channel
4) check balance again (and after some blocks)

**Comment by stefan-mihaila** [comment]
I'm a bit confused by the description of this issue. I skimmed a bit through the code, but not enough to clear up my confusion. Let me know if the following points are correct or not. 

1. The GetInfo gRPC call doesn't return the balance. So subscribing to it isn't that useful for getting the balance.

2. Because the LND API doesn't provide a SubscribeGetInfo method, you built a way to do it with polling in `subscribeGetInfo`. Using this method we can call GetInfo every 5 seconds f.e. and an event will be emitted only if there are changes in whatever GetInfo returns.

3. We have a handler for `subscribeTransactions`. I am not sure when it gets triggered, I assume that when a new onchain tx relevant to the wallet is detected in the mempool? So we can update an amout from the wallet balance in pending when that happens. But I guess it doesn't get triggered when the tx is mined, or on subsequent confirmations, so we don't move that amount from pending into confirmed. Hmm, now that I think about it, if that's the case, maybe here is where `GetInfo` could be useful, as an event would be fired on a new blockheight?

4. We have no handler for `subscribeInvoices`. We somehow compute the new balance when we create invoices / messages in the app, but without calling `getBalanceInformation`. So invoices payed outside of Juggernaut don't get reflected in the app either, do they?

**Comment by johncantrell97** [comment]
Yeah that is my bad when writing this issue. GetInfo does not help you maintain a correct balance.

1.  Yes, correct.
2. Yes, except most of the grpc code is borrowed from Zap (including this 'subscribe get info' idea).
3. Yes, I'm not actually sure exactly when this is triggered.  Given that it includes a number of confirmations field I'd guess maybe it is continually triggered until considered confirmed? If not then it's probably just like you mention, when it first enters the mempool of our node.  I'm already triggering a fetchBalance when we receive this event though.
4. Yea, the subscribeInvoices is only being used to extract messages.    

Overall, it's more complicated than I thought.  Basically a balance can change in a few scenarios:

1) on chain transaction received/sent which I think is covered by the subscribeTransactions.

2) lightning invoice is paid / received.  We could surface the subscribeInvoice data to the renderer process and add a handler that for now only refreshes the balance.  We should probably remove the balance code I added to update the balance when sending/receiving messages in this case as it's better to get the actual data from rpc instead of trying to maintain a balance ourselves.

3) Channel open/closed.  I wonder if this is captured in the transaction subscription since it requires on chain transactions to open and close channels? I would guess it's not entirely captured though and we might have to perform an update on these events as well.

**Comment by stefan-mihaila** [comment]
It looks like `subscribeTransactions` gets called when a tx first enters the mempool, and again on the first confirmation. This is valid for channel txs also. One confirmation might be enough for an amount to be confirmed, or it might not, depending on `bitcoin.defaultchanconfs` in `lnd.conf`. But that's easy to solve, I think we can use `RegisterBlockEpochNtfn` for example that gets called when new blocks are found.

`subcribeInvoices` gets triggered when invoices are payed, but not on payments of invoices. There's a `SubscribeHtlcEvents`, but that's in lnd 0.10 only. So it looks like we still need to do some polling in order to reflect the correct balance.

I'm thinking what a good strategy for polling would be. I might take a look at how Zap tackles this for some inspiration 🙂

**Comment by johncantrell97** [comment]
Hm ok.  Yeah let's take a look at what Zap does in this case as I don't think they use RegisterBlockEpochNtfn or polling to handle this.  I feel like it will be enough to use a combination of subscribeTransactions, subscribeChannelEvents, subscribeInvoices, and our own sendPayment code to trigger balance updates.

The channel events should be fired based on their chan conf settings so we shouldn't have to worry about future blocks.

**Comment by johncantrell97** [comment]
Yeah I just checked and they use the exact list I mentioned in my previous comment.
