### ISSUE TITLE
Relax Message Validation

### ISSUE THREAD

**Issue by apotdevin** [LN-Juggernaut/juggernaut-desktop#20]
Would be great to get the message validation relaxed so that other chat interfaces con talk with Juggernaut.

**Comment by johncantrell97** [comment]
Yes, plan for this is to allow any message through as long as it has message + senderPubKey TLV records.  Instead of rejecting invalid signature we will just store the validity as a new attribute with the message and can then surface it in the ui.

**Comment by apotdevin** [comment]
What is the validity signature validating? That the message is from juggernaut or that its from the correct node?

**Comment by johncantrell97** [comment]
That it's from the node that it says it is.  So when you send a message you sign the TLV payload containing message content, your pubkey, time, message_type, etc.  You then include the signature in the payload itself (kind of like a btc tx).  The receiver can then be sure that the pubKey in the message is the node that actually sent you the message.

If we didn't do this then anyone could send you a message pretending to be anyone else.  I included time,type and other fields in the signature data because I guess in theory someone could then alter any unsigned fields to be anything they want (or replay the message I guess).  

Could obviously relax it to only require signing the content + pubkey and be fine for the most part.

**Comment by apotdevin** [comment]
Ok, yeah makes sense. Thanks for the explanation! Had thought about it for the node but not for all the other fields. Didn't realize these could be tampered

**Comment by apotdevin** [comment]
Hey! Awesome that this got merged in. Was testing it out with ThunderHub and still cant get it to work together. Im getting `Cannot read property requestMessage from null` in `MessageAPI.js`. Looking around and looks like db.messages doesnt find the message thus returns null. Any specific tlv that must be passed with the keysend to be able to store the message on the db?
